package shadersmod.client;

import org.lwjgl.opengl.*;

public class ShaderProgramData
{
    public /* synthetic */ int uniform_heldBlockLightValue;
    public /* synthetic */ int uniform_shadowModelViewInverse;
    public /* synthetic */ int uniform_colortex5;
    public /* synthetic */ int uniform_colortex7;
    public /* synthetic */ int uniform_heldItemId;
    public /* synthetic */ int uniform_eyeBrightness;
    public /* synthetic */ int uniform_fogColor;
    public /* synthetic */ int uniform_normals;
    public /* synthetic */ int uniform_gnormal;
    public /* synthetic */ int uniform_previousCameraPosition;
    public /* synthetic */ int uniform_centerDepthSmooth;
    public /* synthetic */ int uniform_gbufferPreviousProjection;
    public /* synthetic */ int uniform_wetness;
    public /* synthetic */ int uniform_fogMode;
    public /* synthetic */ int uniform_viewWidth;
    public /* synthetic */ int uniform_viewHeight;
    public /* synthetic */ int uniform_shadowAngle;
    public /* synthetic */ int uniform_worldTime;
    public /* synthetic */ int uniform_colortex0;
    public /* synthetic */ int uniform_depthtex1;
    public /* synthetic */ int uniform_eyeBrightnessSmooth;
    public /* synthetic */ int uniform_shadowtex1;
    public /* synthetic */ int uniform_colortex1;
    public /* synthetic */ int uniform_frameTimeCounter;
    public /* synthetic */ int uniform_cameraPosition;
    public /* synthetic */ int uniform_shadowModelView;
    public /* synthetic */ int uniform_sunPosition;
    public /* synthetic */ int uniform_eyeAltitude;
    public /* synthetic */ int uniform_gcolor;
    public /* synthetic */ int uniform_sunAngle;
    public /* synthetic */ int uniform_composite;
    public /* synthetic */ int uniform_rainStrength;
    public /* synthetic */ int uniform_shadowcolor0;
    public /* synthetic */ int uniform_gdepth;
    public /* synthetic */ int uniform_watershadow;
    public /* synthetic */ int uniform_gbufferModelViewInverse;
    public /* synthetic */ int uniform_gbufferModelView;
    public /* synthetic */ int uniform_terrainTextureSize;
    public /* synthetic */ int programIDGL;
    public /* synthetic */ int uniform_skyColor;
    public /* synthetic */ int uniform_gaux2;
    public /* synthetic */ int uniform_shadowtex0;
    public /* synthetic */ int uniform_atlasSize;
    public /* synthetic */ int uniform_tex;
    public /* synthetic */ int uniform_gaux4;
    public /* synthetic */ int uniform_gbufferProjectionInverse;
    public /* synthetic */ int uniform_specular;
    public /* synthetic */ int uniform_shadow;
    public /* synthetic */ int uniform_colortex3;
    public /* synthetic */ int uniform_gbufferProjection;
    public /* synthetic */ int uniform_noisetex;
    public /* synthetic */ int uniform_gbufferPreviousModelView;
    public /* synthetic */ int uniform_moonPosition;
    public /* synthetic */ int uniform_gdepthtex;
    public /* synthetic */ int uniform_colortex2;
    public /* synthetic */ int uniform_near;
    public /* synthetic */ int uniform_aspectRatio;
    public /* synthetic */ int uniform_shadowProjectionInverse;
    public /* synthetic */ int uniform_depthtex2;
    public /* synthetic */ int uniform_gaux3;
    public /* synthetic */ int uniform_shadowProjection;
    public /* synthetic */ int uniform_colortex4;
    public /* synthetic */ int uniform_upPosition;
    public /* synthetic */ int uniform_lightmap;
    public /* synthetic */ int uniform_isEyeInWater;
    public /* synthetic */ int uniform_shadowcolor1;
    public /* synthetic */ int uniform_gaux1;
    public /* synthetic */ int uniform_colortex6;
    public /* synthetic */ int uniform_depthtex0;
    public /* synthetic */ int uniform_terrainIconSize;
    public /* synthetic */ int uniform_hideGUI;
    public /* synthetic */ int uniform_shadowcolor;
    public /* synthetic */ int uniform_moonPhase;
    public /* synthetic */ int uniform_texture;
    public /* synthetic */ int uniform_far;
    
    public ShaderProgramData(final int lllllllllllllIIIllIlIIlIlIlllIII) {
        this.programIDGL = lllllllllllllIIIllIlIIlIlIlllIII;
        this.uniform_texture = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"texture");
        this.uniform_lightmap = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"lightmap");
        this.uniform_normals = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"normals");
        this.uniform_specular = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"specular");
        this.uniform_shadow = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"shadow");
        this.uniform_watershadow = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"watershadow");
        this.uniform_shadowtex0 = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"shadowtex0");
        this.uniform_shadowtex1 = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"shadowtex1");
        this.uniform_depthtex0 = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"depthtex0");
        this.uniform_depthtex1 = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"depthtex1");
        this.uniform_shadowcolor = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"shadowcolor");
        this.uniform_shadowcolor0 = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"shadowcolor0");
        this.uniform_shadowcolor1 = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"shadowcolor1");
        this.uniform_noisetex = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"noisetex");
        this.uniform_gcolor = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"gcolor");
        this.uniform_gdepth = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"gdepth");
        this.uniform_gnormal = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"gnormal");
        this.uniform_composite = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"composite");
        this.uniform_gaux1 = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"gaux1");
        this.uniform_gaux2 = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"gaux2");
        this.uniform_gaux3 = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"gaux3");
        this.uniform_gaux4 = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"gaux4");
        this.uniform_colortex0 = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"colortex0");
        this.uniform_colortex1 = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"colortex1");
        this.uniform_colortex2 = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"colortex2");
        this.uniform_colortex3 = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"colortex3");
        this.uniform_colortex4 = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"colortex4");
        this.uniform_colortex5 = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"colortex5");
        this.uniform_colortex6 = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"colortex6");
        this.uniform_colortex7 = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"colortex7");
        this.uniform_gdepthtex = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"gdepthtex");
        this.uniform_depthtex2 = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"depthtex2");
        this.uniform_tex = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"tex");
        this.uniform_heldItemId = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"heldItemId");
        this.uniform_heldBlockLightValue = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"heldBlockLightValue");
        this.uniform_fogMode = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"fogMode");
        this.uniform_fogColor = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"fogColor");
        this.uniform_skyColor = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"skyColor");
        this.uniform_worldTime = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"worldTime");
        this.uniform_moonPhase = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"moonPhase");
        this.uniform_frameTimeCounter = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"frameTimeCounter");
        this.uniform_sunAngle = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"sunAngle");
        this.uniform_shadowAngle = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"shadowAngle");
        this.uniform_rainStrength = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"rainStrength");
        this.uniform_aspectRatio = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"aspectRatio");
        this.uniform_viewWidth = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"viewWidth");
        this.uniform_viewHeight = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"viewHeight");
        this.uniform_near = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"near");
        this.uniform_far = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"far");
        this.uniform_sunPosition = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"sunPosition");
        this.uniform_moonPosition = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"moonPosition");
        this.uniform_upPosition = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"upPosition");
        this.uniform_previousCameraPosition = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"previousCameraPosition");
        this.uniform_cameraPosition = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"cameraPosition");
        this.uniform_gbufferModelView = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"gbufferModelView");
        this.uniform_gbufferModelViewInverse = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"gbufferModelViewInverse");
        this.uniform_gbufferPreviousProjection = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"gbufferPreviousProjection");
        this.uniform_gbufferProjection = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"gbufferProjection");
        this.uniform_gbufferProjectionInverse = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"gbufferProjectionInverse");
        this.uniform_gbufferPreviousModelView = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"gbufferPreviousModelView");
        this.uniform_shadowProjection = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"shadowProjection");
        this.uniform_shadowProjectionInverse = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"shadowProjectionInverse");
        this.uniform_shadowModelView = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"shadowModelView");
        this.uniform_shadowModelViewInverse = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"shadowModelViewInverse");
        this.uniform_wetness = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"wetness");
        this.uniform_eyeAltitude = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"eyeAltitude");
        this.uniform_eyeBrightness = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"eyeBrightness");
        this.uniform_eyeBrightnessSmooth = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"eyeBrightnessSmooth");
        this.uniform_terrainTextureSize = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"terrainTextureSize");
        this.uniform_terrainIconSize = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"terrainIconSize");
        this.uniform_isEyeInWater = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"isEyeInWater");
        this.uniform_hideGUI = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"hideGUI");
        this.uniform_centerDepthSmooth = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"centerDepthSmooth");
        this.uniform_atlasSize = ARBShaderObjects.glGetUniformLocationARB(lllllllllllllIIIllIlIIlIlIlllIII, (CharSequence)"atlasSize");
    }
}
