package shadersmod.client;

import java.util.*;
import java.nio.*;

public class SMath
{
    static void invertMat4(final float[] lllllllllllllllllIllIllIlllllIll, final float[] lllllllllllllllllIllIllIlllllIlI) {
        lllllllllllllllllIllIllIlllllIll[0] = lllllllllllllllllIllIllIlllllIlI[5] * lllllllllllllllllIllIllIlllllIlI[10] * lllllllllllllllllIllIllIlllllIlI[15] - lllllllllllllllllIllIllIlllllIlI[5] * lllllllllllllllllIllIllIlllllIlI[11] * lllllllllllllllllIllIllIlllllIlI[14] - lllllllllllllllllIllIllIlllllIlI[9] * lllllllllllllllllIllIllIlllllIlI[6] * lllllllllllllllllIllIllIlllllIlI[15] + lllllllllllllllllIllIllIlllllIlI[9] * lllllllllllllllllIllIllIlllllIlI[7] * lllllllllllllllllIllIllIlllllIlI[14] + lllllllllllllllllIllIllIlllllIlI[13] * lllllllllllllllllIllIllIlllllIlI[6] * lllllllllllllllllIllIllIlllllIlI[11] - lllllllllllllllllIllIllIlllllIlI[13] * lllllllllllllllllIllIllIlllllIlI[7] * lllllllllllllllllIllIllIlllllIlI[10];
        lllllllllllllllllIllIllIlllllIll[1] = -lllllllllllllllllIllIllIlllllIlI[1] * lllllllllllllllllIllIllIlllllIlI[10] * lllllllllllllllllIllIllIlllllIlI[15] + lllllllllllllllllIllIllIlllllIlI[1] * lllllllllllllllllIllIllIlllllIlI[11] * lllllllllllllllllIllIllIlllllIlI[14] + lllllllllllllllllIllIllIlllllIlI[9] * lllllllllllllllllIllIllIlllllIlI[2] * lllllllllllllllllIllIllIlllllIlI[15] - lllllllllllllllllIllIllIlllllIlI[9] * lllllllllllllllllIllIllIlllllIlI[3] * lllllllllllllllllIllIllIlllllIlI[14] - lllllllllllllllllIllIllIlllllIlI[13] * lllllllllllllllllIllIllIlllllIlI[2] * lllllllllllllllllIllIllIlllllIlI[11] + lllllllllllllllllIllIllIlllllIlI[13] * lllllllllllllllllIllIllIlllllIlI[3] * lllllllllllllllllIllIllIlllllIlI[10];
        lllllllllllllllllIllIllIlllllIll[2] = lllllllllllllllllIllIllIlllllIlI[1] * lllllllllllllllllIllIllIlllllIlI[6] * lllllllllllllllllIllIllIlllllIlI[15] - lllllllllllllllllIllIllIlllllIlI[1] * lllllllllllllllllIllIllIlllllIlI[7] * lllllllllllllllllIllIllIlllllIlI[14] - lllllllllllllllllIllIllIlllllIlI[5] * lllllllllllllllllIllIllIlllllIlI[2] * lllllllllllllllllIllIllIlllllIlI[15] + lllllllllllllllllIllIllIlllllIlI[5] * lllllllllllllllllIllIllIlllllIlI[3] * lllllllllllllllllIllIllIlllllIlI[14] + lllllllllllllllllIllIllIlllllIlI[13] * lllllllllllllllllIllIllIlllllIlI[2] * lllllllllllllllllIllIllIlllllIlI[7] - lllllllllllllllllIllIllIlllllIlI[13] * lllllllllllllllllIllIllIlllllIlI[3] * lllllllllllllllllIllIllIlllllIlI[6];
        lllllllllllllllllIllIllIlllllIll[3] = -lllllllllllllllllIllIllIlllllIlI[1] * lllllllllllllllllIllIllIlllllIlI[6] * lllllllllllllllllIllIllIlllllIlI[11] + lllllllllllllllllIllIllIlllllIlI[1] * lllllllllllllllllIllIllIlllllIlI[7] * lllllllllllllllllIllIllIlllllIlI[10] + lllllllllllllllllIllIllIlllllIlI[5] * lllllllllllllllllIllIllIlllllIlI[2] * lllllllllllllllllIllIllIlllllIlI[11] - lllllllllllllllllIllIllIlllllIlI[5] * lllllllllllllllllIllIllIlllllIlI[3] * lllllllllllllllllIllIllIlllllIlI[10] - lllllllllllllllllIllIllIlllllIlI[9] * lllllllllllllllllIllIllIlllllIlI[2] * lllllllllllllllllIllIllIlllllIlI[7] + lllllllllllllllllIllIllIlllllIlI[9] * lllllllllllllllllIllIllIlllllIlI[3] * lllllllllllllllllIllIllIlllllIlI[6];
        lllllllllllllllllIllIllIlllllIll[4] = -lllllllllllllllllIllIllIlllllIlI[4] * lllllllllllllllllIllIllIlllllIlI[10] * lllllllllllllllllIllIllIlllllIlI[15] + lllllllllllllllllIllIllIlllllIlI[4] * lllllllllllllllllIllIllIlllllIlI[11] * lllllllllllllllllIllIllIlllllIlI[14] + lllllllllllllllllIllIllIlllllIlI[8] * lllllllllllllllllIllIllIlllllIlI[6] * lllllllllllllllllIllIllIlllllIlI[15] - lllllllllllllllllIllIllIlllllIlI[8] * lllllllllllllllllIllIllIlllllIlI[7] * lllllllllllllllllIllIllIlllllIlI[14] - lllllllllllllllllIllIllIlllllIlI[12] * lllllllllllllllllIllIllIlllllIlI[6] * lllllllllllllllllIllIllIlllllIlI[11] + lllllllllllllllllIllIllIlllllIlI[12] * lllllllllllllllllIllIllIlllllIlI[7] * lllllllllllllllllIllIllIlllllIlI[10];
        lllllllllllllllllIllIllIlllllIll[5] = lllllllllllllllllIllIllIlllllIlI[0] * lllllllllllllllllIllIllIlllllIlI[10] * lllllllllllllllllIllIllIlllllIlI[15] - lllllllllllllllllIllIllIlllllIlI[0] * lllllllllllllllllIllIllIlllllIlI[11] * lllllllllllllllllIllIllIlllllIlI[14] - lllllllllllllllllIllIllIlllllIlI[8] * lllllllllllllllllIllIllIlllllIlI[2] * lllllllllllllllllIllIllIlllllIlI[15] + lllllllllllllllllIllIllIlllllIlI[8] * lllllllllllllllllIllIllIlllllIlI[3] * lllllllllllllllllIllIllIlllllIlI[14] + lllllllllllllllllIllIllIlllllIlI[12] * lllllllllllllllllIllIllIlllllIlI[2] * lllllllllllllllllIllIllIlllllIlI[11] - lllllllllllllllllIllIllIlllllIlI[12] * lllllllllllllllllIllIllIlllllIlI[3] * lllllllllllllllllIllIllIlllllIlI[10];
        lllllllllllllllllIllIllIlllllIll[6] = -lllllllllllllllllIllIllIlllllIlI[0] * lllllllllllllllllIllIllIlllllIlI[6] * lllllllllllllllllIllIllIlllllIlI[15] + lllllllllllllllllIllIllIlllllIlI[0] * lllllllllllllllllIllIllIlllllIlI[7] * lllllllllllllllllIllIllIlllllIlI[14] + lllllllllllllllllIllIllIlllllIlI[4] * lllllllllllllllllIllIllIlllllIlI[2] * lllllllllllllllllIllIllIlllllIlI[15] - lllllllllllllllllIllIllIlllllIlI[4] * lllllllllllllllllIllIllIlllllIlI[3] * lllllllllllllllllIllIllIlllllIlI[14] - lllllllllllllllllIllIllIlllllIlI[12] * lllllllllllllllllIllIllIlllllIlI[2] * lllllllllllllllllIllIllIlllllIlI[7] + lllllllllllllllllIllIllIlllllIlI[12] * lllllllllllllllllIllIllIlllllIlI[3] * lllllllllllllllllIllIllIlllllIlI[6];
        lllllllllllllllllIllIllIlllllIll[7] = lllllllllllllllllIllIllIlllllIlI[0] * lllllllllllllllllIllIllIlllllIlI[6] * lllllllllllllllllIllIllIlllllIlI[11] - lllllllllllllllllIllIllIlllllIlI[0] * lllllllllllllllllIllIllIlllllIlI[7] * lllllllllllllllllIllIllIlllllIlI[10] - lllllllllllllllllIllIllIlllllIlI[4] * lllllllllllllllllIllIllIlllllIlI[2] * lllllllllllllllllIllIllIlllllIlI[11] + lllllllllllllllllIllIllIlllllIlI[4] * lllllllllllllllllIllIllIlllllIlI[3] * lllllllllllllllllIllIllIlllllIlI[10] + lllllllllllllllllIllIllIlllllIlI[8] * lllllllllllllllllIllIllIlllllIlI[2] * lllllllllllllllllIllIllIlllllIlI[7] - lllllllllllllllllIllIllIlllllIlI[8] * lllllllllllllllllIllIllIlllllIlI[3] * lllllllllllllllllIllIllIlllllIlI[6];
        lllllllllllllllllIllIllIlllllIll[8] = lllllllllllllllllIllIllIlllllIlI[4] * lllllllllllllllllIllIllIlllllIlI[9] * lllllllllllllllllIllIllIlllllIlI[15] - lllllllllllllllllIllIllIlllllIlI[4] * lllllllllllllllllIllIllIlllllIlI[11] * lllllllllllllllllIllIllIlllllIlI[13] - lllllllllllllllllIllIllIlllllIlI[8] * lllllllllllllllllIllIllIlllllIlI[5] * lllllllllllllllllIllIllIlllllIlI[15] + lllllllllllllllllIllIllIlllllIlI[8] * lllllllllllllllllIllIllIlllllIlI[7] * lllllllllllllllllIllIllIlllllIlI[13] + lllllllllllllllllIllIllIlllllIlI[12] * lllllllllllllllllIllIllIlllllIlI[5] * lllllllllllllllllIllIllIlllllIlI[11] - lllllllllllllllllIllIllIlllllIlI[12] * lllllllllllllllllIllIllIlllllIlI[7] * lllllllllllllllllIllIllIlllllIlI[9];
        lllllllllllllllllIllIllIlllllIll[9] = -lllllllllllllllllIllIllIlllllIlI[0] * lllllllllllllllllIllIllIlllllIlI[9] * lllllllllllllllllIllIllIlllllIlI[15] + lllllllllllllllllIllIllIlllllIlI[0] * lllllllllllllllllIllIllIlllllIlI[11] * lllllllllllllllllIllIllIlllllIlI[13] + lllllllllllllllllIllIllIlllllIlI[8] * lllllllllllllllllIllIllIlllllIlI[1] * lllllllllllllllllIllIllIlllllIlI[15] - lllllllllllllllllIllIllIlllllIlI[8] * lllllllllllllllllIllIllIlllllIlI[3] * lllllllllllllllllIllIllIlllllIlI[13] - lllllllllllllllllIllIllIlllllIlI[12] * lllllllllllllllllIllIllIlllllIlI[1] * lllllllllllllllllIllIllIlllllIlI[11] + lllllllllllllllllIllIllIlllllIlI[12] * lllllllllllllllllIllIllIlllllIlI[3] * lllllllllllllllllIllIllIlllllIlI[9];
        lllllllllllllllllIllIllIlllllIll[10] = lllllllllllllllllIllIllIlllllIlI[0] * lllllllllllllllllIllIllIlllllIlI[5] * lllllllllllllllllIllIllIlllllIlI[15] - lllllllllllllllllIllIllIlllllIlI[0] * lllllllllllllllllIllIllIlllllIlI[7] * lllllllllllllllllIllIllIlllllIlI[13] - lllllllllllllllllIllIllIlllllIlI[4] * lllllllllllllllllIllIllIlllllIlI[1] * lllllllllllllllllIllIllIlllllIlI[15] + lllllllllllllllllIllIllIlllllIlI[4] * lllllllllllllllllIllIllIlllllIlI[3] * lllllllllllllllllIllIllIlllllIlI[13] + lllllllllllllllllIllIllIlllllIlI[12] * lllllllllllllllllIllIllIlllllIlI[1] * lllllllllllllllllIllIllIlllllIlI[7] - lllllllllllllllllIllIllIlllllIlI[12] * lllllllllllllllllIllIllIlllllIlI[3] * lllllllllllllllllIllIllIlllllIlI[5];
        lllllllllllllllllIllIllIlllllIll[11] = -lllllllllllllllllIllIllIlllllIlI[0] * lllllllllllllllllIllIllIlllllIlI[5] * lllllllllllllllllIllIllIlllllIlI[11] + lllllllllllllllllIllIllIlllllIlI[0] * lllllllllllllllllIllIllIlllllIlI[7] * lllllllllllllllllIllIllIlllllIlI[9] + lllllllllllllllllIllIllIlllllIlI[4] * lllllllllllllllllIllIllIlllllIlI[1] * lllllllllllllllllIllIllIlllllIlI[11] - lllllllllllllllllIllIllIlllllIlI[4] * lllllllllllllllllIllIllIlllllIlI[3] * lllllllllllllllllIllIllIlllllIlI[9] - lllllllllllllllllIllIllIlllllIlI[8] * lllllllllllllllllIllIllIlllllIlI[1] * lllllllllllllllllIllIllIlllllIlI[7] + lllllllllllllllllIllIllIlllllIlI[8] * lllllllllllllllllIllIllIlllllIlI[3] * lllllllllllllllllIllIllIlllllIlI[5];
        lllllllllllllllllIllIllIlllllIll[12] = -lllllllllllllllllIllIllIlllllIlI[4] * lllllllllllllllllIllIllIlllllIlI[9] * lllllllllllllllllIllIllIlllllIlI[14] + lllllllllllllllllIllIllIlllllIlI[4] * lllllllllllllllllIllIllIlllllIlI[10] * lllllllllllllllllIllIllIlllllIlI[13] + lllllllllllllllllIllIllIlllllIlI[8] * lllllllllllllllllIllIllIlllllIlI[5] * lllllllllllllllllIllIllIlllllIlI[14] - lllllllllllllllllIllIllIlllllIlI[8] * lllllllllllllllllIllIllIlllllIlI[6] * lllllllllllllllllIllIllIlllllIlI[13] - lllllllllllllllllIllIllIlllllIlI[12] * lllllllllllllllllIllIllIlllllIlI[5] * lllllllllllllllllIllIllIlllllIlI[10] + lllllllllllllllllIllIllIlllllIlI[12] * lllllllllllllllllIllIllIlllllIlI[6] * lllllllllllllllllIllIllIlllllIlI[9];
        lllllllllllllllllIllIllIlllllIll[13] = lllllllllllllllllIllIllIlllllIlI[0] * lllllllllllllllllIllIllIlllllIlI[9] * lllllllllllllllllIllIllIlllllIlI[14] - lllllllllllllllllIllIllIlllllIlI[0] * lllllllllllllllllIllIllIlllllIlI[10] * lllllllllllllllllIllIllIlllllIlI[13] - lllllllllllllllllIllIllIlllllIlI[8] * lllllllllllllllllIllIllIlllllIlI[1] * lllllllllllllllllIllIllIlllllIlI[14] + lllllllllllllllllIllIllIlllllIlI[8] * lllllllllllllllllIllIllIlllllIlI[2] * lllllllllllllllllIllIllIlllllIlI[13] + lllllllllllllllllIllIllIlllllIlI[12] * lllllllllllllllllIllIllIlllllIlI[1] * lllllllllllllllllIllIllIlllllIlI[10] - lllllllllllllllllIllIllIlllllIlI[12] * lllllllllllllllllIllIllIlllllIlI[2] * lllllllllllllllllIllIllIlllllIlI[9];
        lllllllllllllllllIllIllIlllllIll[14] = -lllllllllllllllllIllIllIlllllIlI[0] * lllllllllllllllllIllIllIlllllIlI[5] * lllllllllllllllllIllIllIlllllIlI[14] + lllllllllllllllllIllIllIlllllIlI[0] * lllllllllllllllllIllIllIlllllIlI[6] * lllllllllllllllllIllIllIlllllIlI[13] + lllllllllllllllllIllIllIlllllIlI[4] * lllllllllllllllllIllIllIlllllIlI[1] * lllllllllllllllllIllIllIlllllIlI[14] - lllllllllllllllllIllIllIlllllIlI[4] * lllllllllllllllllIllIllIlllllIlI[2] * lllllllllllllllllIllIllIlllllIlI[13] - lllllllllllllllllIllIllIlllllIlI[12] * lllllllllllllllllIllIllIlllllIlI[1] * lllllllllllllllllIllIllIlllllIlI[6] + lllllllllllllllllIllIllIlllllIlI[12] * lllllllllllllllllIllIllIlllllIlI[2] * lllllllllllllllllIllIllIlllllIlI[5];
        lllllllllllllllllIllIllIlllllIll[15] = lllllllllllllllllIllIllIlllllIlI[0] * lllllllllllllllllIllIllIlllllIlI[5] * lllllllllllllllllIllIllIlllllIlI[10] - lllllllllllllllllIllIllIlllllIlI[0] * lllllllllllllllllIllIllIlllllIlI[6] * lllllllllllllllllIllIllIlllllIlI[9] - lllllllllllllllllIllIllIlllllIlI[4] * lllllllllllllllllIllIllIlllllIlI[1] * lllllllllllllllllIllIllIlllllIlI[10] + lllllllllllllllllIllIllIlllllIlI[4] * lllllllllllllllllIllIllIlllllIlI[2] * lllllllllllllllllIllIllIlllllIlI[9] + lllllllllllllllllIllIllIlllllIlI[8] * lllllllllllllllllIllIllIlllllIlI[1] * lllllllllllllllllIllIllIlllllIlI[6] - lllllllllllllllllIllIllIlllllIlI[8] * lllllllllllllllllIllIllIlllllIlI[2] * lllllllllllllllllIllIllIlllllIlI[5];
        final float lllllllllllllllllIllIllIlllllIIl = lllllllllllllllllIllIllIlllllIlI[0] * lllllllllllllllllIllIllIlllllIll[0] + lllllllllllllllllIllIllIlllllIlI[1] * lllllllllllllllllIllIllIlllllIll[4] + lllllllllllllllllIllIllIlllllIlI[2] * lllllllllllllllllIllIllIlllllIll[8] + lllllllllllllllllIllIllIlllllIlI[3] * lllllllllllllllllIllIllIlllllIll[12];
        if (lllllllllllllllllIllIllIlllllIIl != 0.0) {
            for (int lllllllllllllllllIllIllIlllllIII = 0; lllllllllllllllllIllIllIlllllIII < 16; ++lllllllllllllllllIllIllIlllllIII) {
                final int n = lllllllllllllllllIllIllIlllllIII;
                lllllllllllllllllIllIllIlllllIll[n] /= lllllllllllllllllIllIllIlllllIIl;
            }
        }
        else {
            Arrays.fill(lllllllllllllllllIllIllIlllllIll, 0.0f);
        }
    }
    
    static void multiplyMat4xMat4(final float[] lllllllllllllllllIllIllllIIIlllI, final float[] lllllllllllllllllIllIllllIIIllIl, final float[] lllllllllllllllllIllIllllIIIllII) {
        for (int lllllllllllllllllIllIllllIIlIIlI = 0; lllllllllllllllllIllIllllIIlIIlI < 4; ++lllllllllllllllllIllIllllIIlIIlI) {
            for (int lllllllllllllllllIllIllllIIlIIII = 0; lllllllllllllllllIllIllllIIlIIII < 4; ++lllllllllllllllllIllIllllIIlIIII) {
                lllllllllllllllllIllIllllIIIlllI[4 * lllllllllllllllllIllIllllIIlIIlI + lllllllllllllllllIllIllllIIlIIII] = lllllllllllllllllIllIllllIIIllIl[4 * lllllllllllllllllIllIllllIIlIIlI + 0] * lllllllllllllllllIllIllllIIIllII[0 + lllllllllllllllllIllIllllIIlIIII] + lllllllllllllllllIllIllllIIIllIl[4 * lllllllllllllllllIllIllllIIlIIlI + 1] * lllllllllllllllllIllIllllIIIllII[4 + lllllllllllllllllIllIllllIIlIIII] + lllllllllllllllllIllIllllIIIllIl[4 * lllllllllllllllllIllIllllIIlIIlI + 2] * lllllllllllllllllIllIllllIIIllII[8 + lllllllllllllllllIllIllllIIlIIII] + lllllllllllllllllIllIllllIIIllIl[4 * lllllllllllllllllIllIllllIIlIIlI + 3] * lllllllllllllllllIllIllllIIIllII[12 + lllllllllllllllllIllIllllIIlIIII];
            }
        }
    }
    
    static void invertMat4FBFA(final FloatBuffer lllllllllllllllllIllIllIlllIlIII, final FloatBuffer lllllllllllllllllIllIllIllIlllll, final float[] lllllllllllllllllIllIllIlllIIlII, final float[] lllllllllllllllllIllIllIllIllIll) {
        lllllllllllllllllIllIllIllIlllll.get(lllllllllllllllllIllIllIllIllIll);
        invertMat4(lllllllllllllllllIllIllIlllIIlII, lllllllllllllllllIllIllIllIllIll);
        lllllllllllllllllIllIllIlllIlIII.put(lllllllllllllllllIllIllIlllIIlII);
    }
    
    static void multiplyMat4xVec4(final float[] lllllllllllllllllIllIlllIlllIIII, final float[] lllllllllllllllllIllIlllIllIlllI, final float[] lllllllllllllllllIllIlllIllIllIl) {
        lllllllllllllllllIllIlllIlllIIII[0] = lllllllllllllllllIllIlllIllIlllI[0] * lllllllllllllllllIllIlllIllIllIl[0] + lllllllllllllllllIllIlllIllIlllI[4] * lllllllllllllllllIllIlllIllIllIl[1] + lllllllllllllllllIllIlllIllIlllI[8] * lllllllllllllllllIllIlllIllIllIl[2] + lllllllllllllllllIllIlllIllIlllI[12] * lllllllllllllllllIllIlllIllIllIl[3];
        lllllllllllllllllIllIlllIlllIIII[1] = lllllllllllllllllIllIlllIllIlllI[1] * lllllllllllllllllIllIlllIllIllIl[0] + lllllllllllllllllIllIlllIllIlllI[5] * lllllllllllllllllIllIlllIllIllIl[1] + lllllllllllllllllIllIlllIllIlllI[9] * lllllllllllllllllIllIlllIllIllIl[2] + lllllllllllllllllIllIlllIllIlllI[13] * lllllllllllllllllIllIlllIllIllIl[3];
        lllllllllllllllllIllIlllIlllIIII[2] = lllllllllllllllllIllIlllIllIlllI[2] * lllllllllllllllllIllIlllIllIllIl[0] + lllllllllllllllllIllIlllIllIlllI[6] * lllllllllllllllllIllIlllIllIllIl[1] + lllllllllllllllllIllIlllIllIlllI[10] * lllllllllllllllllIllIlllIllIllIl[2] + lllllllllllllllllIllIlllIllIlllI[14] * lllllllllllllllllIllIlllIllIllIl[3];
        lllllllllllllllllIllIlllIlllIIII[3] = lllllllllllllllllIllIlllIllIlllI[3] * lllllllllllllllllIllIlllIllIllIl[0] + lllllllllllllllllIllIlllIllIlllI[7] * lllllllllllllllllIllIlllIllIllIl[1] + lllllllllllllllllIllIlllIllIlllI[11] * lllllllllllllllllIllIlllIllIllIl[2] + lllllllllllllllllIllIlllIllIlllI[15] * lllllllllllllllllIllIlllIllIllIl[3];
    }
}
