name: ViaRewind
version: 2.0.2-SNAPSHOT
main: de.gerrygames.viarewind.BukkitPlugin
api-version: 1.13

authors: [Gerrygames]
website: https://viaversion.com/rewind

load: STARTUP
depend: [ViaVersion]
softdepend: [ViaBackwards]
